### PR TITLE
Changed the color chooser on the Midas tag browser to use sliders to select the RGB color

### PR DESCRIPTION
**Pull request by jordanmontt**
Changed the color chooser on the Midas tag browser to use sliders to select the RGB color.

### CODE REVIEW

**Comment by jordanmontt** [comment]
Added initializeWindow method in order to give the give a fixed size. Changed initializeColorChooserPart to use SpRGBSliders instead of just a text field. Changed defaultSpec method to visualize the new color chooser.

**Comment by NicolasAnquetil** [comment]
2 comments:
- could you make the color chooser a separate presenter instead of having it programmed into the TagBrowser ?
  That way we will be able to reuse it.
- on my machine (Linux), the sliders don't work very well, the "thumb" (the control that slides) is either completely on the left or completely on the right, never somewhere in the middle ...

**Comment by jordanmontt** [comment]
> 
> 
> 2 comments:
> 
>     * could you make the color chooser a separate presenter instead of having it programmed into the TagBrowser ?
>       That way we will be able to reuse it.
> 
>     * on my machine (Linux), the sliders don't work very well, the "thumb" (the control that slides) is either completely on the left or completely on the right, never somewhere in the middle ...

- The color chooser is a separate presenter that is called: `SpRGBSliders`. It is initialized in the method `initializeColorChooserPart` of the class  `MiTagManagementPage`. Or maybe I did not understand what do you mean.

- Yes, the sliders does not work well for me too. But it is a Spec problem. What should I do? keep them and wait to a fix in the spec library or find another way to make the color chooser?

**Comment by NicolasAnquetil** [comment]
It would be better with the preview (colorExample) inside SpRGBSliders otherwise it is very difficult to know what color youare choosing.

BUT it means a dependency to Roassal.
I don't think spec depends on Roassal and it would not be cool to add such a dependency.
So if you can think of something else to give the color example.
I tried with a button, but it is difficult to change dynamically the color of a widget, so it should be something you can paint on ...

Maybe ask Esteban

As for the sliders, could you open an issue on spec ?

**Comment by jordanmontt** [comment]
Ok, I can change the Rossal widget for an `SpImagePresenter` and create the color with a form. Doing that It will be no Rossal dependencies, only the sliders along an `SpImagePresenter`.
I will open an issue about the sliders. I have written in the spec channel about that issue too.

**Pull request closed without merging**
