### PR TITLE
Fix baseline with NewTools-Tests

### PR DESCRIPTION
**Pull request by badetitou**
This PR tries to fix the CI broken since https://github.com/moosetechnology/Midas/commit/db5ba1e931a4dc03d2c088769fd09760d2eef729

> I don't know how one can break the CI by using the PR with security checks. We have to verify that

### CODE REVIEW

**Comment by badetitou** [comment]
It is maybe a problem with a cyclic dependency (Moose try to load the last version of Midas that is not this PR)
Do you think we can try a merge @ClotildeToullec?
It fixes the problem on my computer

**Comment by ClotildeToullec** [comment]
I think we should merge. This is necessary anyway

**Comment by ClotildeToullec** [comment]
Ok, this merge is kinda successful: it fixes the previous problem.
Now we have a new issue: Glamour is being removed from Pharo 9 and old browsers still depend on it. I'll try to fix this.
Good thing we started to remove our Glamour dependencies.
Thanks @badetitou

**Comment by jordanmontt** [comment]
Yes, my commit broke the CI, sorry...

**Comment by ClotildeToullec** [comment]
No pb, it's fixed.
I'm working on fixing the Glamour-Tools dependency, we don't want it.

**Pull request merged**
